#!/usr/bin/env bash
set -e

#
# Helpers
##################################################

red="\e[31m"
reset="\e[39m"

run() {
  task=${1}
  shift
  echo -e [${task}] ${@}
  ${@}
}

fail() {
  echo -e ${red}${@}${reset}
  exit 1
}

#
# Commands
##################################################

pluginDir=plugins/verdaccio-oauth-ui

#
# Remove the plugin from node_modules
#
clean() {
  run clean rm -rf .parcel-cache/ dist/ package/ plugins/
}

#
# Build server, config and client
#
build() {
  # copy assets
  run build mkdir -p dist/browser/
  run build cp -R src/client/*.css dist/browser/

  # bundle with parcel
  run build yarn -s parcel build --target browser
  run build yarn -s parcel build --target server
  run build yarn -s parcel build --target cli

  # add node shebang
  printf '%s\n%s\n' '#!/usr/bin/env node' "$(cat dist/cli/index.js)" > dist/cli/index.js
}

#
# Copy the built plugin to node_modules
#
copy() {
  run copy mkdir -p $pluginDir/
  run copy cp -R dist $pluginDir/
  run copy cp package.json $pluginDir/
}

#
# CLI
##################################################

#
# Call the function specified by the first parameter, passing all remaining
# parameters to the function. If no such function exists, display usage info.
#
if [ -n "$1" ] && type $1 | grep -i function > /dev/null; then
  command="$1"
  shift
  $command ${@}
else
  fail "No such command: $1"
fi
